# nginx/default.conf
server {
    listen 80;
    server_name localhost;
    root /var/www;
    index index.php index.html;
    charset utf-8;

    # Security headers (dev-friendly)
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { allow all; log_not_found off; access_log off; }

    location ~ \.php$ {
        internal;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
        access_log off;
        expires 1h;
    }
}